### ISSUE TITLE
Skynet Theme!

### ISSUE THREAD

**Issue by x1PatientZero1x** [home-assistant-community-themes/theme-request#9]
Would love to see a Skynet theme with a terminator background!

**Comment by maartenpaauw** [comment]
Hi @x1PatientZero1x, this organisation contains already existing themes to make it easier for the end user to install them within Home Assistant. Since you didn't submit an url or code for the Skynet Theme I assume you would like to have a theme like this. Feel free to create the theme yourself and submit it afterwards to this organisation. For now i'll close this issue.
